-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Purchase"
local ohTable2 = {
	["Type"] = "PaperPlanter",
	["Amount"] = 1,
	["Category"] = "Eggs"
}

game:GetService("ReplicatedStorage").Events.ItemPackageEvent:InvokeServer(ohString1, ohTable2)


game:GetService("ReplicatedStorage").Events.ItemPackageEvent.OnServerInvoke = function(player, action, data)
    print(player.Name .. " invoked ItemPackageEvent")
    print("Action:", action)
    print("Data:", data.Type, data.Amount, data.Category)

    -- return response to client if needed
    return true
end